const CartActionTypes = {
  INCREASE_ITEM_QUANTITY: "INCREASE_ITEM_QUANTITY",
  DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  CART_TOGGLE: "CART-TOGGLE",
};

export default CartActionTypes;
